"""create_pipeline_webhook_callbacks_table

Revision ID: 0dfcfb1e5ac1
Revises: 5ca4a3e6e474
Create Date: 2026-04-23 18:54:31.576667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dfcfb1e5ac1'
down_revision: Union[str, Sequence[str], None] = '5ca4a3e6e474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_callbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('callback_url', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_callbacks_pipeline_id'), 'webhook_callbacks', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_webhook_callbacks_run_id'), 'webhook_callbacks', ['run_id'], unique=False)
    op.create_index(op.f('ix_webhook_callbacks_tenant_id'), 'webhook_callbacks', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_callbacks_tenant_id'), table_name='webhook_callbacks')
    op.drop_index(op.f('ix_webhook_callbacks_run_id'), table_name='webhook_callbacks')
    op.drop_index(op.f('ix_webhook_callbacks_pipeline_id'), table_name='webhook_callbacks')
    op.drop_table('webhook_callbacks')
    # ### end Alembic commands ###
