"""add_failure_threshold_variables_to_pipeline_circuit_breakers

Revision ID: 43e320d54440
Revises: f74fbd3e4518
Create Date: 2026-04-30 16:42:35.456345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e320d54440'
down_revision: Union[str, Sequence[str], None] = 'f74fbd3e4518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_circuit_breakers', sa.Column('failure_count_threshold', sa.Integer(), nullable=False, server_default="3"))
    op.add_column('pipeline_circuit_breakers', sa.Column('failure_window_minutes', sa.Integer(), nullable=False, server_default="60"))
    
    op.alter_column("pipeline_circuit_breakers","failure_count_threshold",server_default=None,)
    op.alter_column("pipeline_circuit_breakers","failure_window_minutes",server_default=None,)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_circuit_breakers', 'failure_window_minutes')
    op.drop_column('pipeline_circuit_breakers', 'failure_count_threshold')
    # ### end Alembic commands ###
