"""create_pipeline_circuit_breakers_table

Revision ID: 5ca4a3e6e474
Revises: 62b52d3ee60a
Create Date: 2026-04-23 02:42:40.015480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca4a3e6e474'
down_revision: Union[str, Sequence[str], None] = '62b52d3ee60a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_circuit_breakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('retry_after', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_circuit_breakers_pipeline_id'), 'pipeline_circuit_breakers', ['pipeline_id'], unique=True)
    op.create_index(op.f('ix_pipeline_circuit_breakers_tenant_id'), 'pipeline_circuit_breakers', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_circuit_breakers_tenant_id'), table_name='pipeline_circuit_breakers')
    op.drop_index(op.f('ix_pipeline_circuit_breakers_pipeline_id'), table_name='pipeline_circuit_breakers')
    op.drop_table('pipeline_circuit_breakers')
    # ### end Alembic commands ###
