"""create_agent_recommendations_table

Revision ID: 62b52d3ee60a
Revises: 002327702565
Create Date: 2026-04-22 19:25:05.695258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b52d3ee60a'
down_revision: Union[str, Sequence[str], None] = '002327702565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('failure_classification', sa.String(length=50), nullable=False),
    sa.Column('recommended_action', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_recommendations_pipeline_id'), 'agent_recommendations', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_agent_recommendations_run_id'), 'agent_recommendations', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_recommendations_tenant_id'), 'agent_recommendations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_recommendations_tenant_id'), table_name='agent_recommendations')
    op.drop_index(op.f('ix_agent_recommendations_run_id'), table_name='agent_recommendations')
    op.drop_index(op.f('ix_agent_recommendations_pipeline_id'), table_name='agent_recommendations')
    op.drop_table('agent_recommendations')
    # ### end Alembic commands ###
