"""add_callback_url_to_pipelines

Revision ID: 7542d8b846f1
Revises: 0dfcfb1e5ac1
Create Date: 2026-04-23 19:11:12.515647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7542d8b846f1'
down_revision: Union[str, Sequence[str], None] = '0dfcfb1e5ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('callback_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelines', 'callback_url')
    # ### end Alembic commands ###
