from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional

#when we create a pipeline, we just define its name, description. id, created_at are autogenerated by the DB. is_active field also always starts as TRUE
# tenant_id will be in the route itself. Each pipeline is scoped to some specific tenant. 
class PipelineCreate(BaseModel):
    name: str=Field(min_length=1, max_length=255)
    description: Optional[str]=None

# Each pipeline belongs to a specific tenant and that CANNOT be updated
class PipelineUpdate(BaseModel): #we can update the name, description and is_active status
    name: Optional[str]=Field(None, min_length=1, max_length=255)
    description: Optional[str]=None
    is_active: Optional[bool]=None

class PipelineResponse(BaseModel):
    id: int
    tenant_id: int
    name: str
    description: Optional[str]
    created_at: datetime
    is_active: bool

    model_config={
        "from_attributes":True
    }