from pydantic import BaseModel, Field, field_validator
from datetime import datetime
from typing import Optional
from croniter import croniter
from zoneinfo import ZoneInfo

def validate_cron_helper(v: str)->str:
    if not croniter.is_valid(v):
        raise ValueError("Invalid cron expression")
    return v

def validate_timezone_helper(v: str)->str:
    try:
        ZoneInfo(v)
    except Exception:
        raise ValueError("Invalid timezone")
    return v

#when we create a schedule, we just define its cron_expression and timezone. id, created_at are autogenerated by the DB. is_active field also always starts as TRUE
# pipeline_id will be in the route itself. Each schedule is scoped to some specific pipeline. 
class ScheduleCreate(BaseModel):
    cron_expression: str=Field(min_length=1, max_length=100)
    timezone: str=Field(default="UTC", max_length=100)

    # we validate the cron expression and timezone
    @field_validator("cron_expression")
    @classmethod
    def validate_cron(cls,v):
        return validate_cron_helper(v)
    
    @field_validator("timezone")
    @classmethod
    def validate_timezone(cls, v):
        return validate_timezone_helper(v)

# Each schedule belongs to a specific pipeline and that CANNOT be updated
class ScheduleUpdate(BaseModel): #we can update the cron_expression, timezone and is_active status
    cron_expression: Optional[str]=Field(None, min_length=1, max_length=100)
    timezone: Optional[str]=Field(None, max_length=100)
    is_active: Optional[bool]=None

    # we validate the cron expression and timezone
    @field_validator("cron_expression")
    @classmethod
    def validate_cron(cls,v):
        return validate_cron_helper(v)
    
    @field_validator("timezone")
    @classmethod
    def validate_timezone(cls, v):
        return validate_timezone_helper(v)

class ScheduleResponse(BaseModel):
    id: int
    pipeline_id: int
    cron_expression: str
    timezone: str
    created_at: datetime
    is_active: bool

    model_config={
        "from_attributes":True
    }